### ISSUE TITLE
Change in calendar options does not get triggered after refresh

### ISSUE THREAD

**Issue by luigi37** [JWGmeligMeyling/jqm-calendar#30]
My app can change language on the fly.
I change the options of the Calendar to have months and days in another language.
Calling "refresh" does not update the text...
Am I missing anything?
Thanks!

**Comment by luigi37** [comment]
In effect with this code it seems to work:

**Comment by JWGmeligMeyling** [comment]
I never thought of the use of refreshing the calendar for different translations. Both the start day of the week (eg. on sunday or monday) and the labels for the days are rendered in the `init()` function and not in the update function.

See: https://github.com/JWGmeligMeyling/jqm-calendar/blob/master/jw-jqm-cal.js#L80

I think it's quite easy to fix, but unfortunately I wont have the time for this now..

**Comment by luigi37** [comment]
Thanks, I will give it a try and if succesfull I'll commit the changes... 
Do you mean I should move
the start day of the week (eg. on sunday or monday) and the labels for the days
to refresh() ?

**Comment by JWGmeligMeyling** [comment]
Yes I meant that, but I believe you already found out 😉

**Comment by luigi37** [comment]
I did not find an easy way to do that... thanks for any code change from your side :-)

**Comment by JWGmeligMeyling** [comment]
Then i'll reopen. Unfortunately I don't have the time to get involved on this issue now :cry:

**Comment by luigi37** [comment]
Thanks a lot :-)

**Comment by luigi37** [comment]
Hi Jan, any update here? Got the first user noticing it :-) ...

**Comment by JWGmeligMeyling** [comment]
I would suggest just destroying the calendar and creating another one with the new settings object. I have no time to investigate this issue in the next few weeks.

**Comment by luigi37** [comment]
Hi Jan,
that would have created the need to reassociate the events and stuff I added....
I created a pull request which add an id to each day label and through that change it on the fly...
Let me know it ok and if you can merge
Thanks

**Comment by luigi37** [comment]
Change implemented
