### ISSUE TITLE
Ignore button when searching for events

### ISSUE THREAD

**Issue by ikennah** [JWGmeligMeyling/jqm-calendar#31]
This is a good plug-in just found, but I am struggling with the events.  I saw the code on the guide on how to look for events, but clicking on the previous and next button to switch between months also triggers an event. Is it possible to stop the button's from triggering an event and only trigger an event when you click on a date?

**Comment by ikennah** [comment]
closing issue commenting out line 125
    ` if ( selected ) $a.click();`

**Comment by ikennah** [comment]
closing fixed the issue by commenting out line 155
if ( selected ) $a.click();

**Comment by JWGmeligMeyling** [comment]
👍🏻
