### ISSUE TITLE
Buttons to change year

### ISSUE THREAD

**Issue by luigi37** [JWGmeligMeyling/jqm-calendar#32]
Would it be possible to add year buttons (maybe in a inner position compared to the months buttons) to enable a quick move from year to year?
Thanks!
Luigi

**Comment by JWGmeligMeyling** [comment]
Yes, I think this would be possible. We could refresh the calendar to a date `new Date(curDate.getFullYear() - 1, .., ..)`.

**Comment by luigi37** [comment]
Note: maybe better: arrow-d for previous year and arrow-u for next year
