### ISSUE TITLE
Disable past dates

### ISSUE THREAD

**Issue by ikennah** [JWGmeligMeyling/jqm-calendar#33]
I really like this calender but I am struggling with preventing past date. Is there a way to prevent the user from clicking on a past date. possibly greying it out.

**Comment by luigi37** [comment]
+1 here. Only difference is that I would need to disable dates after actual date... In add to not being able to click, user should also not be able to move months forward (or backward in previous case)...

**Comment by JWGmeligMeyling** [comment]
Create a function "isDisabled()" which takes a date an returns a boolean. Create a default implementation in defaults thats returns false: `function() { return false; }`. If you need an other implementation, provide it through settings: `{ isDisabled: function(date) { return date.valueOf() < (new Date()).valueOf(); }}`. Then adjust the cell renderer to set: `$element.attr("disabled", options.isDisabled(curDate)`.

When done, please create a PR.

**Comment by ikennah** [comment]
Now I've time to start looking at this, I am not sure I follow the last section Then adjust the cell renderer to set:  `$element.attr("disabled", options.isDisabled(curDate).` can you elaborate

**Comment by JWGmeligMeyling** [comment]
That should work!

**Comment by ikennah** [comment]
This is what I added, but obviously I am missing something. not working.     
   
      function isDisabled(date){
        return date.valueOf() < (new Date()).valueOf();  
      }
       
       //Disabling the elements
      $element.attr('disabled', options.isDisabled(curDate));

**Comment by luigi37** [comment]
Updated code. Can someone check if it works properly?

**Comment by luigi37** [comment]
hmmm... the option 0 (don't disable dates) and -1 (disable past dates) seems to work properly  in the latest code.
For some reason the option 1 (disable future dates) once moving to next month still show available first week... not sure why...

**Comment by luigi37** [comment]
Ok solved (my mistake in dateOnly function)
