### ISSUE TITLE
eventhandler must contain all events in order to work

### ISSUE THREAD

**Issue by mikerodd** [JWGmeligMeyling/jqm-calendar#34]
Hi, 
I defined custom eventHandler but in odrer to work, you need to redefine all events (even if don't want to). 
I modified the way the settings are defaulted adding true to the recursive. This way, undefined events are correctly defaulted
plugin.settings = $.extend(true, defaults, options);

it solved my problem :-) 

I quit new to github and I don't know if I must/can submit a patch for such simple modification ?

**Comment by JWGmeligMeyling** [comment]
Yes you can submit a patch :smile: 
You can do this by creating a fork of the repository, cloning your fork to your local system, making the changes, adding the changes, committing the changes, then pushing the commit to your fork repository. From there you can make a pull request to my repository.

**Comment by luigi37** [comment]
@mikerodd which line should be modified in js file? Thanks

**Comment by luigi37** [comment]
This one?

    function init() {
         plugin.settings = $.extend({}, defaults, options);

to


    function init() {
         plugin.settings = $.extend(true, defaults, options);

?

**Comment by JWGmeligMeyling** [comment]
Yes, that should be the line. I think it prevents the default events being overridden by the options.

**Comment by luigi37** [comment]
Added suggested improvement
