### ISSUE TITLE
Wrong next month

### ISSUE THREAD

**Issue by monkiki** [JWGmeligMeyling/jqm-calendar#36]
Hi there,

When you are on August and click on "Next (month)", the next shown is "October".

Please, test at http://jsfiddle.net/Gajotres/f6xeE/light/ also tested locally and "September" is missing.

Thanks in advance.

**Comment by monkiki** [comment]
BTW Today is August 31, which seems to be the problematic date.

**Comment by JWGmeligMeyling** [comment]
My first idea is that the calendar uses the current date as base, and then simply adds a month (a date which obviously does not exist in September). Should be easy fix, but I am currently occupied.

**Comment by JWGmeligMeyling** [comment]
Try to change:
```js
refresh(new Date(plugin.settings.date.getFullYear(), plugin.settings.date.getMonth() + 12, plugin.settings.date.getDate()));
```
to:
```js
refresh(new Date(plugin.settings.date.getFullYear(), plugin.settings.date.getMonth() + 12, 1));

```
in: https://github.com/JWGmeligMeyling/jqm-calendar/blob/master/jw-jqm-cal.js#L84 (and a few lines above it as well for previous)

**Comment by monkiki** [comment]
Cool! Thanks a lot!

**Comment by JWGmeligMeyling** [comment]
Did that work? :smile:  If so, would you maybe want to submit a PR?

**Comment by luigi37** [comment]
May I suggest the following logic?
Same day if exist in previous/next month, last day available if it does not exist...
Testing now and putting on my branch if it works...

Something like:

$("<a href='#' data-role='button' data-icon='arrow-r' data-iconpos='notext' class='next-btn'>Next</a>").click(function() {
            refresh(new Date(plugin.settings.date.getFullYear(), plugin.settings.date.getMonth() + 1, 
                plugin.settings.date.getDate()<=_daysInMonth(new Date(plugin.settings.date.getFullYear(), plugin.settings.date.getMonth() + 1))?plugin.settings.date.getDate():_daysInMonth(new Date(plugin.settings.date.getFullYear(), plugin.settings.date.getMonth() + 1))
                             
                             
            ));
         }).appendTo($th);

**Comment by monkiki** [comment]
@JWGmeligMeyling your fix don't seem to work properly :(

**Comment by luigi37** [comment]
Same zone as indicated by Jan.
But it does not work..  Try 15 Aug and in September it will go on 30. Not sure why...
Jan solution works but if takes you always to day 1.
Not sure which logic is more... Logic!

**Comment by JWGmeligMeyling** [comment]
@monkiki I am sorry I was pointing at the wrong line of code. It should obviously change the line for the button that goes to the next month, and not the next year. Maybe thats why it didn't work as expected. 
@luigi37 We could possible do this... I would opt for trying the same date if exists, and otherwise default to the first day. We can either break your expression apart and see where its broke, or we do the following: first we calculate the day the old way, then we compare the actual month of the date with the incremented month, if it differs we generate it again with the previous date first set to day 1.

**Comment by luigi37** [comment]
Ok, I think that probably make more sense to keep always the day of the previous month except when it exceed the number of days of the next...
So... 15 remains always 15 and 31 becomes 30 or 28 in Feb and so on... drawback is that when you go back you remain to that day but I think we cal live with that...

The code should (for month forward):
    
$("<a href='#' data-role='button' data-icon='arrow-r' data-iconpos='notext' class='next-btn'>Next</a>").click(function() {
            var newDay= plugin.settings.date.getDate();
            var maxDay=_daysInMonth(new Date(plugin.settings.date.getFullYear(), plugin.settings.date.getMonth() + 1),0);
            alert(newDay+" "+maxDay+" it was: "+plugin.settings.date.getDate()); //debug only
            if (newDay>maxDay) {newDay=maxDay;}            
            refresh(new Date(plugin.settings.date.getFullYear(), plugin.settings.date.getMonth() + 1, newDay));
         }).appendTo($th);

Problem is that, despite tapping on another day (let's say today is the 1st of Sept and I click on 15th of Sept), the variable 
    plugin.settings.date.getDate()
remain always "1"

Any idea why?

**Comment by JWGmeligMeyling** [comment]
When the day doesn't exist, the Date will move into the future.
```js
a = new Date(2015, 9, 31) // Sat Oct 31 2015 00:00:00 GMT+0100 (CET), oct has 31 days, nov 30
a = new Date(a.getFullYear(), a.getMonth() + 1, 31) // Tue Dec 01 2015 00:00:00 GMT+0100 (CET)
```
Think of it as follows: first you increment the month, you get at a hypothetical 31 november. Then it figures out that november has only 30 days. So the date is subtracted with 30 days, and the date is moved `n` days into the future, just like how we skip single days:
```js
a = new Date(2015, 9, 31) 
Sat Oct 31 2015 00:00:00 GMT+0100 (CET)
a = new Date(2015, 9, 31 + 1) 
Sun Nov 01 2015 00:00:00 GMT+0100 (CET)
```

**Comment by luigi37** [comment]
Hi Jan, that makes sense.
Anyway what I get stuck with is...
After calling

    refresh(new Date(plugin.settings.date.getFullYear(), plugin.settings.date.getMonth() + 1, newDay));

I assume that

    plugin.settings.date.getDate()

Would contain the NEW day of the month (which ideally would be the one selected on the calendar) BUT for some reason in my code it goes back to 1....

Not sure why.... the alert in my code is a kind of showing this behaviour for debug purposes...

**Comment by JWGmeligMeyling** [comment]
Thats strange. I will debug this in a moment :D

**Comment by luigi37** [comment]
Hi Jan, I'm still struggling.... Any luck from your side? Thanks!

**Comment by JWGmeligMeyling** [comment]
I am currently very occupied with the development of Devhub and my bachelors, and did not find any time to work on this yet. If anyone has an urgent need to get this fixed, feel free to contact me. Otherwise, just wait a week or two and I'll look in to it in some free time.

**Comment by luigi37** [comment]
Ok, it seems I discovered the way to update the date object:

I added

       plugin.settings.date = date ;

in both functions below

        function cellTapholdHandler() {
         var $this = $(this),
	 date = $this.data('date');
         $tbody.find("button.ui-btn-active").removeClass("ui-btn-active");
         $this.addClass("ui-btn-active");
         
         if ( date.getMonth() !== plugin.settings.date.getMonth() ) {
            // Go to previous/next month
            refresh(date);
         } 
	 // Select new date
	 $element.trigger('change', date);
	 $element.trigger('taphold', date);
         
         plugin.settings.date = date ;
      }
      
      
      function cellClickHandler() {
         var $this = $(this),
         date = $this.data('date');
         $tbody.find("button.ui-btn-active").removeClass("ui-btn-active");
         $this.addClass("ui-btn-active");
         
         if ( date.getMonth() !== plugin.settings.date.getMonth() ) {
            // Go to previous/next month
            refresh(date);
         } else {
            // Select new date
            $element.trigger('change', date);
         }
         plugin.settings.date = date ;
      }


Behaviour seems consistent, please test it....

**Comment by luigi37** [comment]
After some tests I think it works. I'm going to pull it in the main repository

**Comment by JWGmeligMeyling** [comment]
For me this works as well :smile:  Thanks for the contribution. Is there any reason to keep this issue open for now?

**Comment by luigi37** [comment]
I think not. I'm closing it. Thanks!

**Comment by monkiki** [comment]
Thanks!
