### ISSUE TITLE
new Date(2015,09,05,10,30) format shows up 1 month later

### ISSUE THREAD

**Issue by omni181** [JWGmeligMeyling/jqm-calendar#40]
When using the `new Date(2015,09,05,10,30)` format for dates, the event shows up 1 month later. In this case, October instead of September.
Dates in the format of: `new Date("2015-09-05T10:30")` show the event on the correct month.

**Comment by jwgmeligmeyling** [comment]
This is no bug; this is how Javascript behaves. The string constructor should not be used anyway, it behaves differently across various browsers and in most browsers it does not even work. The constructor that takes the integers, starts counting months from 0 (for januari).

**Comment by JWGmeligMeyling** [comment]
This is no bug; this is how Javascript behaves. The string constructor should not be used anyway, it behaves differently across various browsers and in most browsers it does not even work. The constructor that takes the integers, starts counting months from 0 (for januari).

**Comment by JWGmeligMeyling** [comment]
This is no bug; this is how Javascript behaves. The string constructor should not be used anyway, it behaves differently across various browsers and in most browsers it does not even work. The constructor that takes the integers, starts counting months from 0 (for januari).
