### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by BigG** [JWGmeligMeyling/jqm-calendar#41]
Hi there,

there is something strange that happen when I try to refresh the list of events.
So my situation is this one:
- user explore the calendar and let's say an event is showed into listview
- now the user come back to another view and add some events
- users can now check if the event just created is the calendar view

How can I trigger the refresh of the listview?
$("#calendar").trigger("refresh"); seems not working as well as $("#calendar").trigger('refresh', date); where date is today.

Can you help me, please?

Thanks!

**Comment by jwgmeligmeyling** [comment]
I think you end up having two calendar instances and updating the wrong one. Please provide a JSfiddle or something so we can see the problem in the context of your application.

**Comment by BigG** [comment]
Hey, thank you for your quick answer.
In short this is the action related to the click on "Check Calendar View". All the event come out from a db. 

``` js
$('#checkCalendarView').on('click', function (e) {

    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();

    var arr = [];

    database.transaction(function(tx) {
             tx.executeSql('SELECT * FROM eventLog', [], function(tx, results) {
                var len = results.rows.length;
                for (var i = 0; i < len; i++) {
                var begin = createDate(results.rows.item(i).data+ " " +results.rows.item(i).hour);

                     arr.push({
                        "summary": results.rows.item(i).type,
                        "begin": begin,
                        "end": begin
                    });

                }



                 $("#calendar").jqmCalendar({
                    events : arr,
                    months: ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"],
                    days: ["Do","Lu", "Ma", "Me", "Gi", "Ve", "Sa"],
                    startOfWeek: 1
                }, []);



        }, function(err) {
                console.log('ERROR Events: ' + JSON.stringify(err));
            });
                });

        });
```

In addition I checked this on your .js

``` js
$.fn.jqmCalendar = function(options) {
      return this.each(function() {
         if (!$(this).data('jqmCalendar')) {
             $(this).data('jqmCalendar', new $.jqmCalendar(this, options));
         }

      });
```

And if I create a new istance the old one is of course showed and the new one is correctly populated. 

Where I am doing wrong?

Thanks!

**Comment by jwgmeligmeyling** [comment]
Currently, a new events array can't be passed as options parameter for the update call. That should have been implemented but we never got to it. Have a look at this comment to see how to work around: https://github.com/JWGmeligMeyling/jqm-calendar/issues/12#issuecomment-31121742

**Comment by JWGmeligMeyling** [comment]
Err strange thats what you're actually doing. Is this how you create the calendar or how you update it?

**Comment by jwgmeligmeyling** [comment]
You can't do this this way.

You should have something like this:

``` js
var arr = [];

$('#view').on('pageinit', function() {
             $("#calendar").jqmCalendar({
                events : arr,
                months: ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"],
                days: ["Do","Lu", "Ma", "Me", "Gi", "Ve", "Sa"],
                startOfWeek: 1
            });
});

$('#checkCalendarView').on('click', function (e) {
database.transaction(function(tx) {
         tx.executeSql('SELECT * FROM eventLog', [], function(tx, results) {
            var len = results.rows.length;
            for (var i = 0; i < len; i++) {
            var begin = createDate(results.rows.item(i).data+ " " +results.rows.item(i).hour);

                 arr.push({
                    "summary": results.rows.item(i).type,
                    "begin": begin,
                    "end": begin
                });

            }



             $("#calendar").trigger('update');
    })
})
```

**Comment by BigG** [comment]
Ahhh I see the point. Nice solution!
Have you any idea how to manage doubled entry?

**Comment by jwgmeligmeyling** [comment]
Clear the array first. http://stackoverflow.com/a/1232046/2104280

**Comment by BigG** [comment]
Peerfeect!! 
Sometimes I forget the basics... ;)

Btw great plugin, really!

**Comment by jwgmeligmeyling** [comment]
Life would have been so much easier if they just added a `clear()` function to the array :wink: Glad you like it and the plugin is still being used! (It's from 2013 :blush: )

**Comment by BigG** [comment]
Hi there, all works as expected but there is a strange behaviour when users change day in calendar view. So basically even if events are already there (and the dot is showed just under the number) if a tap on the previous day and then I tap again on the fully populated day, no event is showed. It is seems like all is cleaned up. Do you think I need to listen to every change? I mean if my array is already populated do I need to repopulate again at every change?

Let me know..
BigG

**Comment by jwgmeligmeyling** [comment]
Strange, haven't seen this before. Is the same happening in the example? Then it might be an issue, if not, please share your event handler.
