### ISSUE TITLE
Calendar not working in  Compiled APP.

### ISSUE THREAD

**Issue by Nganyu** [JWGmeligMeyling/jqm-calendar#44]
I have the plugin working very well on my browser but not displaying on my app page. That is i compile my app with adnroid studio and page no more loads calendar. I have added a refresh button on the page through javascript. it works on my browser yet app page still loads empty. Thank you. I have even compiled and tested the demo from this page and still does not work in app.. what could be the issue. Thanks in advance

**Comment by jwgmeligmeyling** [comment]
Never had any problems with code minifications. You're probably just not loading the source. Please provide a stack trace or error message, because the problem is untraceable in the way its currently phrased.
