### ISSUE TITLE
Problems to see the correct Date 

### ISSUE THREAD

**Issue by goedecke** [JWGmeligMeyling/jqm-calendar#46]
When i use the data the field month or day get me -1 if i use the month 03 the calendar show me febrary 

![image](https://cloud.githubusercontent.com/assets/512404/21822261/22fdeb5c-d73c-11e6-93c2-2f6a42d61e6a.png)

**Comment by luigi37** [comment]
Hi
That's the way java script handles months. It starts from zero and goes to 11
