### ISSUE TITLE
Display evends in the calendar

### ISSUE THREAD

**Issue by lali1589** [JWGmeligMeyling/jqm-calendar#47]
I have been using jqm-calendar for a while now and i need to be able to show event information right in the calendar is it possible ?

**Comment by jwgmeligmeyling** [comment]
Yes you could program that.

**Comment by lali1589** [comment]
I am trying to access the events and at getImportanceofDay the event is always undefined. maybe i am doing it wrong!!! any help is appreciated


plugin.settings.eventHandler.getImportanceOfDay(date, **defaults.events**,
            function(importance) {
              if ( importance > 0 ) {
                  
                  $a.append("<span>"+**defaults.events**+"</span>");
              }

              if ( date.getFullYear() === today.getFullYear() &&
                   date.getMonth() === today.getMonth() &&
                   date.getDate() === today.getDate() ) {
                  $a.addClass("ui-btn-today");
              } else {
                  $a.addClass("importance-" + importance.toString());
              }
         });
